name: Generate docu-lite outline

on: [push]

jobs:
  outline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # ← this is critical
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install docu-lite
        run: |
          python -m pip install docu-lite 

      - name: Run docu-lite
        run: |
          python -m docu-lite
          python -m docu-lite --config docu-lite-docmode.ini

      - name: Commit docu-lite-outline.html if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docu-lite-outline.html docu-lite-style.css docu-lite.ini
          git diff --cached --quiet || git commit -m "Update outline files"
          git push
